i already have an env file with NEXT_PUBLIC_VERCEL_URL=mp-propertymanage
even the sync button doesn't work too, it returns an error

Try fixing this error: `Console Error: Error: Attempted to call getUnit(

Try fixing this error: `Console Error: FirebaseError: Missing or insuffi

no, i already deployed the firebase rules on the console

on add bookings, switch to drop down for existing agent instead of addin

can you add an option to add another unit to an investor, i have few inv

can you also allow backtracking for the "add bookings"? I wanna add some

now back to the sync and calendar sync, it's still not working

Try fixing this error: `Console Error: FirebaseError: Missing or insuffi

the authentication, can you add an option to save password?

why is it slow though? when i press unit, it's just on loading units, sa

Try fixing this error: `Runtime Error: FirebaseError: Missing or insuffi

where is the changes

Try fixing this error: `Runtime Error: Error: 2 UNKNOWN: Getting metadat

Runtime ErrorServer

Error: 2 UNKNOWN: Getting metadata from plugin fail

Try fixing this error: `Runtime Error: Error: 2 UNKNOWN: Getting metadat

i already double checked it, it's already deployed and exactly as you sp

Try fixing this error: `Runtime Error: Error: Firebase Admin SDK initial

what do i put in FIREBASE_SERVICE_ACCOUNT_KEY

Try fixing this error: `Runtime Error: Error: Firebase Admin SDK initial

Try fixing this error: `Runtime Error: Error: The default Firebase app d

i already put the code as env on vercel

ITS FULL OF ERRORS, go back to firebase auth

Revert "ITS FULL OF ERRORS, go back to firebase auth"

This reverts commit 2f5d611a921b41bfba36a9a8053c367a724fe14e.

Revert "i already put the code as env on vercel"

This reverts commit e56af4ebec138e03ed22560e01ea7a615f70cbba.

Revert "Try fixing this error: `Runtime Error: Error: The default Firebase app d"

This reverts commit bfd9abe6216911635f84545661b8e7fa67ab1dbe.

Revert "Try fixing this error: `Runtime Error: Error: Firebase Admin SDK initial"

This reverts commit 451a1cd2fc1a64a69cdf7e23f3c1aac301cf14fd.

Revert "what do i put in FIREBASE_SERVICE_ACCOUNT_KEY"

This reverts commit 27da3e3fd91a058bb138627232706eb3deb41579.

Revert "Try fixing this error: `Runtime Error: Error: Firebase Admin SDK initial"

This reverts commit 196789447d9c2ea0696083d798e84b8c8ab4b8f4.

Revert "i already double checked it, it's already deployed and exactly as you sp"

This reverts commit 640ef98d900b95c480581c1ee464255f0c9a0507.

Revert "Try fixing this error: `Runtime Error: Error: 2 UNKNOWN: Getting metadat"

This reverts commit ae570deb3ca0ecf8705148c4bdbfb80dcd750224.

Revert "Runtime ErrorServer"

This reverts commit 82fe73a5a9d221547dd0242bd9f7078a053d9057.

Revert "Try fixing this error: `Runtime Error: Error: 2 UNKNOWN: Getting metadat"

This reverts commit 899356ac7ca4f22bdda0d1539ed52a20ff19a149.

Revert "where is the changes"

This reverts commit 49ebd05e8965bee9358c4d3b0f37904025375423.

Revert "Try fixing this error: `Runtime Error: FirebaseError: Missing or insuffi"

This reverts commit 6f6f8d61f7e616eeac3a83ded75075299a258fa5.

Revert "why is it slow though? when i press unit, it's just on loading units, sa"

This reverts commit 64ff8287771fc52b7ddbac4feebceebee196591d.

Revert "the authentication, can you add an option to save password?"

This reverts commit 97d01d06d20a9ab8c9293830e76981d80cc68498.

Revert "Try fixing this error: `Console Error: FirebaseError: Missing or insuffi"

This reverts commit 8a8a16ef338547b5053e38c8725ff5d31c85e88b.

Revert "now back to the sync and calendar sync, it's still not working"

This reverts commit 79d72a0f0f88bef0b27830c75b2506a5672c6882.

Revert "can you also allow backtracking for the "add bookings"? I wanna add some"

This reverts commit 42cee2d6a3f3b352e8c5a548969e0bcba4c1f074.

Revert "can you add an option to add another unit to an investor, i have few inv"

This reverts commit 0303d8ee1add2ca4170d3b347266c92f2cba929b.

Revert "on add bookings, switch to drop down for existing agent instead of addin"

This reverts commit 302e381b49ca9a97b383cb2a93cd636d74eebb32.

Revert "no, i already deployed the firebase rules on the console"

This reverts commit 8800e422a9f44a8b974dc7cc7b058be30dd84b0c.

Revert "Try fixing this error: `Console Error: FirebaseError: Missing or insuffi"

This reverts commit b3f0c5412f58f2c4e837e83bb06ed006515ff02d.

Revert "Try fixing this error: `Console Error: Error: Attempted to call getUnit("

This reverts commit 7c87914232c455a18f1e37f875143bb9d551b44f.

Revert "even the sync button doesn't work too, it returns an error"

This reverts commit e06f1c11b7415b99127407b57f3a8e14fb601ae0.

Revert "i already have an env file with NEXT_PUBLIC_VERCEL_URL=mp-propertymanage"

This reverts commit 83bfa10eaa5af82427a29e49f7290453adccc145.

Revert "i cant find the reauthenticating"

This reverts commit 2e38d5341f2e5158dd673b514feb67300118a82b.